### ISSUE TITLE
Memory and timing increasing

### ISSUE THREAD

**Issue by L3o-pold** [marcopacini/ts-prometheus#2]
Metrics are kept forever in RAM until rebooting process. `/metrics` call will take more and more times too. It can be an issue for long live process.

Maybe we should clean stored metrics after some times.

**Comment by marcopacini** [comment]
If you are talking about `Summary` metric, then you are right. It miss a [sliding time window](https://prometheus.io/docs/concepts/metric_types/#summary) functionality that I hope to can implement soon.
