### ISSUE TITLE
Extra result when get metrics

### ISSUE THREAD

**Issue by galiazzi** [marcopacini/ts-prometheus#6]
When getting the metrics an extra information "http_requests_total 0" was returned. 
How do I ignore this extra result?

Example code:

```ts
import {
  Counter,
  Registry,
} from "https://deno.land/x/ts_prometheus@v0.2.0/mod.ts";

const counter = Counter.with({
  name: "http_requests_total",
  help: "The total number of HTTP requests.",
  labels: ["method", "status"],
});

const totalGetCreate = counter.labels({
  method: "GET",
  status: "201",
});

totalGetCreate.inc();
totalGetCreate.inc(42);

console.log(Registry.default.metrics());
```

Result:
```
# HELP http_requests_total The total number of HTTP requests.
# TYPE http_requests_total counter
http_requests_total 0
http_requests_total{method="GET",status="201"} 43
```

Expected result:
```
# HELP http_requests_total The total number of HTTP requests.
# TYPE http_requests_total counter
http_requests_total{method="GET",status="201"} 43
```

Deno Version: 
```
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by justinmchase** [comment]
I came here to report this exact same issue as well.

**Comment by justinmchase** [comment]
I believe its this line:
https://github.com/marcopacini/ts_prometheus/blob/9740fee980185fd9f7afa7856f0799530024c123/gauge.ts#L34

It seems like that is adding the label-less metric, which is fine if you don't add labels but adding the labels is a second api call which then doesn't clear out the label-less metrics and so you get both.

**Comment by marcopacini** [comment]
Thank you for the report. I can fix it but before I'd like to discuss about what output do you expect if `inc` would never called. For example consider this code:

```ts
const counter = Counter.with({
  name: "http_requests_total",
  help: "The total number of HTTP requests.",
  labels: ["method", "status"],
});

const totalGetCreate = counter.labels({
  method: "GET",
  status: "201",
});

console.log(Registry.default.metrics());
```

If `counter` won't be showed then `totalGetCreate` should not be shown either. My only concern is about never show metrics not still used. It is right? What do you think?

**Comment by justinmchase** [comment]
It should show no metrics. No data is itself a data point and there is a function in prometheus for detecting this condition.

https://prometheus.io/docs/prometheus/latest/querying/functions/#absent
